version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/cloudability/metrics-agent

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Install / run dep
          command: |
            go get -u github.com/golang/dep/cmd/dep
            dep ensure -v

      - run:
          name: Install golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0

      - run:
          name: Install helm
          command: |
            curl -sfL https://get.helm.sh/helm-v3.0.3-linux-amd64.tar.gz | tar xz && mv linux-amd64/helm /bin/helm && rm -rf linux-amd64

      - run: 
          name: Lint
          command: make lint
          no_output_timeout: 20m

      - run:
          name: Run Tests
          command: make test

      - setup_remote_docker:
            version: 17.07.0-ce

      - run:
          name: build docker container
          command:  make -e container-build

      - run:
          name: package helm chart
          command: make -e helm-package

      - run:
          name: push to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} 
                make -e dockerhub-push
            fi

      - store_test_results:
          path: /tmp/test-results