version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8

jobs:

  snyk_scan:
    docker:
      - image: 'circleci/golang:1.14'
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          organization: Cloudability
          monitor-on-build: true
          severity-threshold: medium


  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/cloudability/metrics-agent

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Install golangci-lint
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0

      - run: 
          name: Lint
          command: make lint
          no_output_timeout: 20m

      - run:
          name: Run Tests
          command: make test

      - setup_remote_docker:
            version: 17.07.0-ce

      - run:
          name: build docker container
          command:  make -e container-build

      - run:
          name: push to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} 
                make -e dockerhub-push 
            fi

      - store_test_results:
          path: /tmp/test-results
workflows:
  workflow:
    jobs:
      - snyk_scan:
          context: snyk

      - build:
          context: metrics-agent-master-build
          filters:
            branches:
              only:
                - master
