apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-agent.fullname" . }}
  labels:
    {{- include "metrics-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "metrics-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "metrics-agent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "metrics-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - 'kubernetes'
          env:
            - name: "CLOUDABILITY_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "metrics-agent.fullname" . }}
                  key: CLOUDABILITY_API_KEY
            {{- if .Values.extraEnv }}
            {{ toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
            - name: CLOUDABILITY_CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: CLOUDABILITY_POLL_INTERVAL
              value: {{ .Values.pollInterval | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
