name: Master

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v2
          with:
            go-version: '1.14'
        - uses: actions/checkout@v2
        - name: build docker container
          run: make -e container-build
        - name: docker tag
          run: make docker-tag
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - if: github.ref == 'refs/heads/master'
          - name: push to dockerhub
            run: make dockerhub-push
        - if: github.ref == 'refs/heads/beta'
          - name: push to dockerhub
            run: make dockerhub-push-beta

  slackFinish:
    name: Notify Finish
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: 8398a7/action-slack@v3
        with:
          fields: repo,message,commit,author,action,eventName,ref,workflow
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

