name: Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v2
      - name: build docker container
        run: make -e container-build
      - name: push to dockerhub
        run: |
          if [ "${GITHUB_REF}" == "master" ]; then
              docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
              make -e dockerhub-push
          fi
