name: Master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - uses: actions/checkout@v2
      - name: build docker container
        run: make -e container-build
      - name: docker tag
        run: make docker-tag
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push to dockerhub
        run: make dockerhub-push